canonical/manual-tls-certificates-operator

src/charm.py, tests/unit/test_charm.py
Adds validation that certificates are properly encoded in base64
=> Adds validation that certificates are properly encoded in base64

.github/ISSUE_TEMPLATE/bug_report.md
=> Adds bug report template

lib/charms/tls_certificates_interface/v1/tls_certificates.py
=> Bumps lib to version 1.8

.github/workflows/promote.yaml
Adds a charmhub promote job to CI.
=> Adds a charmhub promote job to CI

.github/workflows/promote.yaml
[Bug fix] Uses the correct environment variable for charmhub auth
=> [Bug fix] Uses the correct environment variable for charmhub auth

lib/charms/tls_certificates_interface/v1/tls_certificates.py
Update `tls-certificates-interface` library to get new Provider initiated revocation feature.
=> Update tls-certificates-interface library

.github/workflows/main.yml
Previous PR did not specify sudo for snap install.
=> Use sudo for snap install

.github/workflows/main.yml
Publish the charm file downloaded from Github artifacts.
=> Move downloaded artifact charm where charmcraft can find it

.github/workflows/main.yml, charmcraft.yaml, tests/integration/test_integration.py
Just changed the os version across to 22.04
=> [ISSUE-29] Upgrading to 22.04 jammy

.github/workflows/main.yml, charmcraft.yaml, tox.ini
Archive charmcraft and juju logs on integration tests failure
=> Archive logs on integration tests failure

.github/workflows/main.yml, .github/workflows/promote.yaml
Uses `upload-charm` workflow to upload charm.
=> Uses `upload-charm` workflow to upload charm

.github/workflows/promote.yaml
Standardises around charmcraft token environment variable (to match with main workflow)
=> Standardises around charmcraft token environment variable

lib/charms/tls_certificates_interface/v2/tls_certificates.py, src/charm.py, tests/unit/test_charm.py
Uses tls-certificates-interface lib v2.1.
Fixes #41
=> [Feat] Uses tls-certificates-interface lib v2.1

README.md, actions.yaml, lib/charms/tls_certificates_interface/v2/tls_certificates.py, requirements.txt, src/charm.py, tests/integration/test_integration.py, tests/unit/test_charm.py
**[this PR](https://github.com/canonical/tls-certificates-interface/pull/62) needs to be merged first.**
Uses the latest lib
Implements actions to allow passing certs manually
Adds test cases
=> Implements providing certificates manually

docs/index.md
Fix the navigation bar in Charmhub documentation
=> Fix Charmhub documentation

README.md, tests/integration/test_integration.py
Small improvement to the README
=> Adds charm deployment command in README

.github/ISSUE_TEMPLATE/bug_report.md
Although the GitHub markdown parser is pretty forgiving, this follows best practices and should work with most markdown parsers.
=> Update markdown to follow best practices

.github/ISSUE_TEMPLATE/bug_report.md
This seems like it might lead to cleaner bug reports, but I don't have anything to support that.. just an opinion, take it or leave it :laughing: 
The main benefit would be when someone doesn't fill out a section (say, screenshots or logs) and just ignores it (i.e. doesn't manually remove all the text). With comments, it won't have a bunch of placeholder text in it when they submit, the section would just be empty.
=> Bug issue template - with comments!

lib/charms/tls_certificates_interface/v2/tls_certificates.py
Fetches latest tls_certificates lib
=> Fetches latest tls_certificates lib

.github/workflows/main.yml, .github/workflows/promote.yaml
Bumps the versions of charming-actions in the charm
=> Bumps charming actions version

.github/workflows/promote.yaml
Uses base image 22.04 for ubuntu instead of the default 20.04
=> Uses base image 22.04 for ubuntu instead of the default 20.04

README.md, lib/charms/tls_certificates_interface/v2/tls_certificates.py
Modifies deploy command in README and fetches latest lib
=> Modifies deploy command in README and fetches latest lib

renovate.json
Adds renovate config file to avoid having to manually create PR's for lib updates.
=> chore: Adds renovate config file

lib/charms/tls_certificates_interface/v2/tls_certificates.py
Bumps tls lib version. This PR fixes #77
=> chore: Bumps tls lib version

.github/workflows/update-libs.yaml
Adds update-libs workflow to create PRs automaticaclly to update charm libraries.
The workflow will run every 12 hours.
This PR should not be merged before[ IS ticket ](https://portal.admin.canonical.com/C160234/)is resolved and `TELCO_GITHUB_BOT_TOKEN` secret is added.
=> feat: Adds update-libs workflow

.github/workflows/update-libs.yaml
Adds a missing character in update-libs.yaml file
=> fix: Adds a missing character in update-libs.yaml file

.github/workflows/update-libs.yaml
Fixes PR title created by bot in update-libs
=> fix: Fixes PR title created by bot in update-libs

.github/workflows/main.yml
bump juju version from 3.1 to 3.4.
=> chore: bump juju to 3.4

.github/workflows/main.yml
=> chore: bump microk8s to v.1.29

lib/charms/tls_certificates_interface/v3/tls_certificates.py
Bump tls lib to v3.5.
Fixes #174
=> chore: bump tls lib to v3.5

.github/workflows/dependabot_pr.yaml, .github/workflows/main.yml, pyproject.toml, tests/integration/test_integration.py, tests/unit/test_charm.py, tox.ini
- Automates dependabot PR review and merge
- Improves tox config and fixes related issues
- Adds concurrency job to cancel currently running CI actions when a new commit is pushed on the same branch. (Excludes main from this logic)
=> feat: Automates dependabot PR review and merge

.github/workflows/build.yaml, .github/workflows/integration-test.yaml, .github/workflows/promote.yaml, .github/workflows/publish-charm.yaml, tests/integration/test_integration.py
Adds workflow files to build, test and promote charm on `arm64` and `amd64`
=> feat: Adds workflows to build and publish the charm on arm64

lib/charms/tls_certificates_interface/v4/tls_certificates.py, tests/unit/test_charm.py, tests/unit/test_helpers.py
=> chore: Use tls lib V4.0

lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py, lib/charms/tempo_coordinator_k8s/v0/tracing.py, lib/charms/tls_certificates_interface/v4/tls_certificates.py, src/charm.py
- Tracing libs have moved, this PR fetches the new ones
- Fetches the latest tls lib
=> chore: Fetch new tracing and latest tls libs

tests/integration/test_integration.py
This PR fixes the flakiness in the integration tests by waiting for the `tls-requirer` application to be in an active state before continuing.
We also remove the cleanup fixture, reusing the already deployed applications to speed up the execution time by a factor of ~1.5.
=> fix: Speed up integration tests and fix flakiness

.github/renovate.json5, .github/workflows/trivy.yaml
- Enable Trivy scan.
- Enable Renovate on `latest`
=> feat: Enable Trivy scan

.github/workflows/main.yaml
=> build: Run main workflow on latest branch
