metadata.yaml, src/charm.py, tests/integration/test_integration.py, tests/unit/test_charm.py, tox.ini
This PR changes the use of `StoredState` to peer relations to enable scaling. The state will be stored in the peer relation app bucket. When using only one unit, the behavior stays the same. However, when adding additional units, only the leader will be able to access the state and respond to certificate request. This will prevent issues when using the `self_signed_certificate` option, where each unit would provide different certificates.
=> Feature: Support scaling by using peer relations

.github/workflows/main.yml, metadata.yaml, tests/integration/test_integration.py
Removes the placeholder image. This is not actually needed, and without it this charm will likely work on both machines and Kubernetes :rocket: This will need to be verified and probably backed up by a test, but this PR removes the image either way, as it's not used for anything and not required for deployment on Kubernetes.
EDIT: Bonus updating the CI to run all the tests on a PR.
=> refactor: remove placeholder image resource

.gitignore, requirements.txt, src/self_signed_certificates.py, tests/integration/test_integration.py, tests/unit/test_charm.py
- This PR addresses the issue reported [here](https://github.com/canonical/tls-certificates-operator/issues/14).
- This PR passes the extensions set on the CSR to the certificate. 
- The certificate builder version has been set to `x509.Version.v3` to add support for extensions such as the `SubjectAlternativeName`
=> Added extensions support in the certificate generation

actions.yaml, src/charm.py, tests/unit/test_charm.py
Feature request to add an action to generate
certificates along with private key. Currently
the charms can relate to tls-certificates-operator charm and request for certificates via the integration. An action is required to request for certificate by a non-charmed application.
Microstack (aka sunbeam) [1] is one such example which requests certificate via actions.
[1] https://github.com/openstack-snaps/snap-microstack
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Add action to generate certificates

.github/workflows/publish.yml, charmcraft.yaml, tests/unit/test_charm.py
The currently published charm on charmhub's edge channel is broken. It is a weird beast built on 22.04 but trying to run on 20.04.
The `publish` action uses `destructive` mode, and it will by default use a base matching the underlying system. Since we are using `ubuntu-latest` in the workflow and we have a base defined for 22.04, when `ubuntu-latest` started pointing to 22.04, the build broke.
This PR changes the workflow to pin the version to 20.04 and also removes the base for 22.04.
It also includes a small fix for a flaky test introduced in the last PR.
=> Fix charm build

.github/workflows/main.yml
Last PR introduced changes to the workflow for publishing the charm by using charmcraft directly. It however was missing a step to install charmcraft.
=> Install charmcraft before using it

lib/charms/tls_certificates_interface/v1/tls_certificates.py
Existing logs spit out warnings on every `update_status` event for as long as the charm references `TLSCertificatesRequiresV1`. This is very annoying. Have dropped warning to `DEBUG`.
Example:
```
unit-kafka-0: 17:30:14 WARNING unit.kafka/0.juju-log No relation: certificates
unit-zookeeper-1: 17:31:24 WARNING unit.zookeeper/1.juju-log No relation: certificates
unit-zookeeper-2: 17:32:15 WARNING unit.zookeeper/2.juju-log No relation: certificates
unit-zookeeper-0: 17:32:17 WARNING unit.zookeeper/0.juju-log No relation: certificates
unit-kafka-0: 17:34:46 WARNING unit.kafka/0.juju-log No relation: certificates
unit-zookeeper-1: 17:36:25 WARNING unit.zookeeper/1.juju-log No relation: certificates
unit-zookeeper-2: 17:37:29 WARNING unit.zookeeper/2.juju-log No relation: certificates …
```
=> chore: drop noisy update_status warnings to debug

CODEOWNERS, README.md, config.yaml, src/charm.py
Deprecates the use of self-signed certificates feature. People requiring self-signed certificates in the Juju world should now use the [self-signed-certificates operator](https://charmhub.io/self-signed-certificates).
=> Deprecates the use of self-signed certificates feature

README.md, config.yaml, src/charm.py, tests/unit/test_charm.py
Given the TLS certificate operator already provides the possibility of configuring the period of validity of the certificates, it makes sense to allow to specify the validity for CA certificate as well, when generating the CA/certs. If these modifications sounds sensible, I would be more than happy to introduce them in the new charm https://github.com/canonical/self-signed-certificates-operator. Although this behaviour in this charm is now deprecated, we still need this feature for a use-case which is still on juju 2.9.42+.
=> Add ca-certificate-validity config option

.github/workflows/main.yml, tests/integration/test_integration.py, tox.ini
Adds requirer charm to the integration tests:
- Checks if certificate is provided using the get-certificate action of the tls-requirer-operator charm
=> Adds requirer charm to the integration tests

README.md, actions.yaml, lib/charms/tls_certificates_interface/v2/tls_certificates.py, src/charm.py, tests/unit/test_charm.py
Merges actions get-outstanding-certificate-requests and get-certificate-request into one action that has an optional `relation-id` param.
Depends on https://github.com/canonical/tls-certificates-interface/pull/67
=> Merges actions get-outstanding-certificate-requests and get-certificate-request

.github/ISSUE_TEMPLATE/bug_report.md
This change makes proper use of github labels for the bug report, instead of tagging the title with "[BUG]"
We could also make use of [GitHub issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) -- but they currently don't support a way to let users upload files. This feature is still in beta, so maybe it is best to just use this markdown template for now.
Live test on my fork: https://github.com/DanielArndt/tls-certificates-operator/issues/new/choose
=> Use label for bug reports instead of putting text in the title

README.md, src/charm.py, tests/integration/test_integration.py, tests/unit/test_charm.py
The goal is to add CSR validation to the `provide-certificate` action in the TLS Certificates Operator. 
This PR implements https://github.com/canonical/tls-certificates-operator/issues/59 
If the CSR provided is not found on the `requirer` the action fails.
The validation over the CSR is done using an existing method in the TSL certificates library that compares the CSR and the certificate `public_key` and `subject`
=> Add CSR validation

src/charm.py, src/helpers.py, tests/unit/test_charm.py, tests/unit/test_helpers.py
Add validation of the CA chain in the TLS-certificates operator `provide-certificate` action. 
To validate we use the x509 certificate method `verify_directly_issued_by` which checks the certificate issuer name matches the issuer subject name and thatthe certificate is signed by the issuer's private key.
Implements https://github.com/canonical/tls-certificates-operator/issues/58
=> Validate ca chain

src/charm.py, tests/integration/test_integration.py
Integration tests failed after https://github.com/canonical/tls-certificates-requirer-operator/issues/13 was merged.
`tls-certificates-requirer-operator` status after being deployed is not `active` anymore. 
The check over its status was removed from the integration tests.
Plus minor fix for the static job.
=> Fix failing integration tests

.github/workflows/main.yml, README.md, actions.yaml, metadata.yaml, src/charm.py, tests/integration/test_integration.py, tests/unit/test_charm.py
Changes charm name to `manual-tls-certificates`. Please wait for the charm name to be updated in charmhub before merging this here. Ref: https://discourse.charmhub.io/t/change-charm-name-in-charmhub/12174
=> chore: Changes charm name to `manual-tls-certificates`

README.md, src/charm.py, tests/integration/test_integration.py
This change removes the scaling restriction on the `manual-tls-certificates` charm.
This charm is workloadless, and can operate fine with scaling. That being said, the `tls-certificates-interface` that it depends on seems to hardcode some restrictions to the leader unit. This means that all actions need to be performed on the leader unit.
I'm honestly not sure what the best approach is. This was the quickest, but we could also update the `tls-certificates-interface` to support non-leader units.
I fear that there may be some edge cases around when the charm is scaled relative to other operations.
=> feat: Remove scaling restriction

src/charm.py, tests/integration/test_integration.py, tests/unit/test_charm.py
Fixes get-outstanding-certificates-requests action
Uses Json string the result output
Fixes unit tests
Fixes issue #79
=> fix: Fixes get-outstanding-certificates-requests action

.github/dependabot.yml
`pip-compile` is not the right value to put in the Dependabot configuration file, but needs to be simply `pip`.
=> fix: Fix dependabot configuration, replacing pip-compile with pip

.github/dependabot.yml
Dependabot's PR currently fail the PR linting stage. This PR aims to fix that by adding a "chore: " prefix.
=> fix: Fix Dependabot PR titles

tests/integration/test_integration.py
The tls-certificates requirer doesn't store ca chains anymore and won't return them in the `get-certificate` juju action (reference below). Here when we run the `get-certificate` action, we don't look at the ca chain anymore. This fixes an issue currently in main that prevents integration tests from running correctly.
- https://github.com/canonical/tls-certificates-requirer-operator/pull/39
=> fix: Remove chain validation from integration tests

actions.yaml, src/charm.py, src/helpers.py, tests/unit/test_helpers.py
Make ca-chain an optional parameter. 
Fixes #157 
It doesn't make much sense for `ca-chain` to be a required parameter. Especially in contexts of self-signed certificates.
=> feat: make ca-chain an optional parameter

src/charm.py, tests/integration/test_integration.py, tests/unit/test_charm.py
Address an issue where the charm would return an error message when the user didn't provide the relation id in the `provide-certificate` juju action.
Fixes #177
=> fix: provide-certificates when relation id is not provided

.github/workflows/main.yml
Charmcraft currently does not work with the latest lxd version (5.21/stable). This prevents other PR's being merged as CI is failing. This change freezes lxd to 5.20/stable. 
- https://github.com/canonical/charmcraft/issues/1640
=> fix: freeze lxd to 5.20/stable

src/charm.py, tests/unit/test_charm.py
Here we centralize and simplify charm status management using the `collect-status` event handler.
The intent is to standardise and simplify status management accross all TLS owned charms. 
- https://ops.readthedocs.io/en/latest/#ops.CharmEvents.collect_unit_status
=> chore: centralise status management using collect status

tests/integration/conftest.py, tests/integration/test_integration.py, tox.ini
Currently, ruff is only configured to check the files for linting errors. This adds ruff formatting to tox checks.
Review notes:
Only tox.ini contains functional changes, the rest are the result of running tox -e format.
=> style: Format using ruff

test-requirements.txt
I'm not sure what happened here, but `backports-strenum==1.3.1`  doesn't work on Python 3.11 or above, so this shouldn't have been included here.
This was likely an issue upstream that has been addressed.
All I did was re-run the pip-compile command with the same python version
=> build: re-compile pip dependencies

.github/workflows/main.yaml
The work for publishing the charm was changed to the shared workflow for a single architecture, but this charm is built for both `amd64` and `arm64`. The publish job was not working because it could not find the right artifact.
This switches to the multiarch workflow to get the right artifact per architecture.
=> fix: Use multiarch publish workflow

.github/workflows/promote.yaml
```
error: snap "charmcraft" is not available on 1/stable but is available to
install on the following tracks:
```
=> fix: Use latest/stable when installing charmcraft in the promote workflow

src/charm.py, tests/unit/test_charm.py
Action provide-certificate fails with KeyError when ca-chain option is not provided.
If user does not provide ca-chain as action params, use [certificate, ca-certificate] as ca-chain.
Fixes: https://github.com/canonical/manual-tls-certificates-operator/issues/157
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> fix: use ca-certificate as ca-chain if not provided
